apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-front-redisazure
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: mddcontainerregistry.azurecr.io/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "demoaks.redis.cache.windows.net"
        - name: REDIS_PWD
          value: "kPIdjKnVlli6JNraXb1aUZZIxK6jnvQX8lhpP2x55YU="


---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front-redisazure
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front
