version: '3'
services:
#  azure-vote-back:
#    image: redis
#    container_name: azure-vote-back
#    ports:
#        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: azure-vote-front
    container_name: azure-vote-front-azureredis
    environment:
      REDIS: mddredis.redis.cache.windows.net
      REDIS_PWD: aEhLd9XGW7ALopFADQOlUS8VNG4YC0dUp+lRDcSzei0=
    ports:
        - "8080:80"
